# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net
name: PickleProjectMessaging

on:
  push:
    branches: [ main ]
    paths: Application/*
  pull_request:
    branches: [ main ]
    paths: Application/*
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
env:
  registryName: g4y55h2kdmxpsmpnpreg.azurecr.io
  repositoryName: techboost/dotnetcoreapp
  dockerFolderPath: ./Application/src/RazorPagesTestSample
  tag: ${{github.run_number}}


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy ARM template
    - name: Run ARM deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./InfrastructureAsCode/main.bicep
        parameters: environment=${{ env.targetEnv }}
